### ISSUE TITLE
Choosing someone outside the initial 8

### ISSUE THREAD

**Issue by alldritt** [ShadeApps/SHDCircularView#2]
Hi,

Playing with the example application and I wonder how one selects a person outside the initial group of 8 displayed in the view.  Is there a gesture for cycling through all the people?

**Comment by ShadeApps** [comment]
Hello!

Unfortunately, there is no such option as the control was intended for a limited number of people. I could actually take some time and create a selector list as a separate to choose and remove people? as well as displaying the whole list at once. 

#1

**Comment by alldritt** [comment]
Thanks for replying.  I can appreciate that dealing with an unbounded list makes this much more complicated.  Perhaps some gesture for circling through the people.  Anyway, nice work.
